# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LWBeautyKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LWBeautyKit

  target 'LWBeautyKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LWBeautyKitUITests' do
    # Pods for testing
  end

end
